# Generated by Django 2.1.5 on 2019-01-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20190116_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobbie',
            name='author',
            field=models.ManyToManyField(blank=True, to='members.Profile'),
        ),
    ]
