# Generated by Django 2.1.5 on 2019-01-16 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20190116_0252'),
    ]

    atomic = False
    operations = [
        migrations.RenameModel(
            old_name='Hobbie',
            new_name='Hobby',
        ),
    ]
